#!/bin/bash
#SBATCH --nodes=1 --exclusive
#SBATCH --ntasks-per-node=6
#SBATCH --cpus-per-task=2
#SBATCH --time=5:00:00
#SBATCH --output=Outs/out_p_6_t_2_N_1024.out
#SBATCH --nodelist=c4n6


NAME="Lab3"
mpic++ -o $NAME $NAME.cpp -fopenmp
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
numactl --cpunodebind=0 --membind=0 srun --mpi pmix $NAME 1024
